docs: enrich migration guide
catenax-ng/tx-tractusx-edc pull request #1
Opened 2023-03-17 08:05 UTC by ndr-brt

PR migrated from https://github.com/catenax-ng/product-edc/pull/818

2023-03-17 10:53 UTC, florianrusch-zf requested changes
Just found some markdown linting problems

2023-03-17 10:53 UTC, florianrusch-zf commented on docs/migration/Version_0.1.x_0.3.x.md
> +- refactored the HTTP server contexts (more details on the [related decision record](https://eclipse-edc.github.io/docs/#/submodule/Connector/docs/developer/decision-records/2022-11-09-api-refactorin
```suggestion

- refactored the HTTP server contexts (more details on the [related decision record](https://eclipse-edc.github.io/docs/#/submodule/Connector/docs/developer/decision-records/2022-11-09-api-refactoring/renaming)). They need to be refactored as:
```

2023-03-17 10:53 UTC, florianrusch-zf commented on docs/migration/Version_0.1.x_0.3.x.md
> +## Deprecation
```suggestion

## Deprecation
```

2023-03-17 10:53 UTC, florianrusch-zf commented on docs/migration/Version_0.1.x_0.3.x.md
>  - Supported `/public` data plane endpoint without trailing slash, that can be eventually removed from the configuration
```suggestion

- Supported `/public` dataplane endpoint without trailing slash, that can be eventually removed from the configuration
```

2023-03-17 13:45 UTC, florianrusch-zf approved these changes

2023-03-20 06:19 UTC, paullatzelsperger approved these changes

2023-03-20 06:20 UTC, merged